name: "Meeting"
on:
  issue_comment:
    types: [created, edited]
jobs:
  meeting:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        # 0 indicates all history
        fetch-depth: 0
    - uses: cutenode/action-meeting@dev
      with:
        markdown-join-instructions: .github/meeting/how-to-join.md
        markdown-minutes-base: .github/meeting/base.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
        agenda-label: meet-agenda
        invites: '@bnb'
        observers: '@cutenode-bot'
